version: '3'
services:

  redis:
    image: redis:4.0.5-alpine

    hostname: redis
    ports:
      - 6379:6379

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017

  mongo_import:
    build: ./dump
    links:
      - mongodb
